language: node_js
node_js:
  - '8'
  - '10'
  - '12'

cache:
  directories:
    - node_modules

install:
  - yarn install --ignore-engines

script:
  - echo $(npm_tag)
  - yarn lint
  - yarn test
  - yarn build-clean
after_success:
  - "[ $TRAVIS_NODE_VERSION == '12' ] && yarn coveralls"

before_script: |
  function npm_tag() {
    CURRENT_VERSION=$(node -e "console.log(require('./package.json').version)")
    PRERELEASE_TAG_REGEX="[0-9]+\.[0-9]+\.[0-9]+-([a-z]+)\.[0-9]+"
    if [[ $CURRENT_VERSION =~ $PRERELEASE_TAG_REGEX ]]; then
      echo "${BASH_REMATCH[1]}"
    else
      echo "latest"
    fi
  }

deploy:
  skip_cleanup: true
  provider: npm
  email: tannerntannern@gmail.com
  api_key:
    secure: JWUZaEwM1JBIgnvThYDU2xEwl1TwY6eOhvxkbPiCZlDgf/2j5gokxas6xW9sAr97wIXpEAGkgp1a+IWN23maijOyp/7e2pLiS3rYKP2S1YGvDipu66bg8XUfJtok+axjFU+5bmBo5siulfBC6H4MxW+wUaF4Wo1f1tf85qWjLCI2/KOWAc2gSpQsGUlwcJCxny/hZcDtzUMfmRZC8uGenHRFZrDlCVQZrdoIxKgMwXDaoP5OL9FSgswinDHqS5SM2O+P9wkAn86//8neay50/atsA4AWx3vVseQOZFPQSOvk4Zr3UaKBObg7SdU7SK5CRzI0mYN+AgAA68fvMCGN2jvD4Ye60vHVJCvaPYv+G0RxhzK/nNc40wdJ3+vc/JFTJ/jkJsrRzmSmv5X863hqOtez40orCz9P26ggr5qT/KUn4Pup2/HazipqYM0SZkR8PEjEnx3hm2l/HoqdC1v6A8HuY2CxFppOvtx3Lm2IsS46x7fXkeB0ATk8uotjmeJ+oE65Q1h62+hXD87t/LO3ztcK9YVx5ATKqAYdeZMi2Y9jwt256I8PTVxWSCUtxZMQBb7+4+ksFOFRNTXRwlGNXPbXfZdYPgGP+qcJOacfwldJZcTo5SevB5aPawq5BXAVnP23zyx8OJPhtJHZTlG6UzoiJc8VBUMghd5lV5X7BAA=
  on:
    tags: true
    node: '12'
    repo: tannerntannern/ts-mixer
  # TODO: this isn't working
  tag: $(npm_tag)
