language: node_js
node_js:
- '6'
- '8'

before_script:
- npm install
script:
- npm run lint
- npm run test
after_success:
- npm run coverage
- npm run coveralls

cache:
  directories:
  - node_modules

deploy:
  provider: npm
  email: tannerntannern@gmail.com
  api_key:
    secure: JWUZaEwM1JBIgnvThYDU2xEwl1TwY6eOhvxkbPiCZlDgf/2j5gokxas6xW9sAr97wIXpEAGkgp1a+IWN23maijOyp/7e2pLiS3rYKP2S1YGvDipu66bg8XUfJtok+axjFU+5bmBo5siulfBC6H4MxW+wUaF4Wo1f1tf85qWjLCI2/KOWAc2gSpQsGUlwcJCxny/hZcDtzUMfmRZC8uGenHRFZrDlCVQZrdoIxKgMwXDaoP5OL9FSgswinDHqS5SM2O+P9wkAn86//8neay50/atsA4AWx3vVseQOZFPQSOvk4Zr3UaKBObg7SdU7SK5CRzI0mYN+AgAA68fvMCGN2jvD4Ye60vHVJCvaPYv+G0RxhzK/nNc40wdJ3+vc/JFTJ/jkJsrRzmSmv5X863hqOtez40orCz9P26ggr5qT/KUn4Pup2/HazipqYM0SZkR8PEjEnx3hm2l/HoqdC1v6A8HuY2CxFppOvtx3Lm2IsS46x7fXkeB0ATk8uotjmeJ+oE65Q1h62+hXD87t/LO3ztcK9YVx5ATKqAYdeZMi2Y9jwt256I8PTVxWSCUtxZMQBb7+4+ksFOFRNTXRwlGNXPbXfZdYPgGP+qcJOacfwldJZcTo5SevB5aPawq5BXAVnP23zyx8OJPhtJHZTlG6UzoiJc8VBUMghd5lV5X7BAA=
  on:
    tags: true
    branch: master
    node: '8'
    repo: tannerntannern/ts-mixer
